// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOBt1CzhV5lyjWCHES7Vu7w8AzTa8y8c0',
    appId: '1:479514889011:web:d4aa321266e92635444c46',
    messagingSenderId: '479514889011',
    projectId: 'nancy-shop-c87fe',
    authDomain: 'nancy-shop-c87fe.firebaseapp.com',
    storageBucket: 'nancy-shop-c87fe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7FHvBhPd7DbM2ShUk7KFxYrE2ufVZeiw',
    appId: '1:479514889011:android:ea72b75c2b75a658444c46',
    messagingSenderId: '479514889011',
    projectId: 'nancy-shop-c87fe',
    storageBucket: 'nancy-shop-c87fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHcdbdtnd74MwMdGeZdE-Kh22NxiYWQwg',
    appId: '1:479514889011:ios:caab00306e9522dd444c46',
    messagingSenderId: '479514889011',
    projectId: 'nancy-shop-c87fe',
    storageBucket: 'nancy-shop-c87fe.appspot.com',
    iosBundleId: 'com.example.eCommerce',
  );
}
